.TH "Case" 3 "Vendredi 3 Janvier 2020" "Version sp5_03.01.2020" "SDA 2019-20 Ruban de Möbius" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Case
.SH SYNOPSIS
.br
.PP
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "typeCase \fBtype\fP"
.br
.ti -1c
.RI "\fBVec3\fP \fBcrd\fP"
.br
.ti -1c
.RI "bool \fBvisite\fP"
.br
.ti -1c
.RI "bool \fBdans_chemin\fP"
.br
.ti -1c
.RI "unsigned int \fBordre\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour SDA 2019-20 Ruban de Möbius à partir du code source\&.
