.TH "C:/PJ_SDA/item.cpp" 3 "Vendredi 3 Janvier 2020" "Version sp5_03.01.2020" "SDA 2019-20 Ruban de Möbius" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/PJ_SDA/item.cpp \- Composant Item Structures de données et algorithmes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'item\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBafficher\fP (const \fBItem\fP &it)"
.br
.RI "Affiche la version chaîne de caractères d'un item\&. "
.in -1c
.SH "Description détaillée"
.PP 
Composant Item Structures de données et algorithmes\&. 

Projet DesprésGr109NougaretGr109 
.PP
\fBAuteur\fP
.RS 4
Antoine Després, Anicet Nougaret 
.RE
.PP
\fBVersion\fP
.RS 4
1 06/01/20 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "void afficher (const \fBItem\fP & it)"

.PP
Affiche la version chaîne de caractères d'un item\&. 
.PP
\fBParamètres\fP
.RS 4
\fIit\fP Item à afficher 
.RE
.PP
\fBPrécondition\fP
.RS 4
Il existe une fonction string permettant de convertir le type représenté par un Item en chaîne de caractères\&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour SDA 2019-20 Ruban de Möbius à partir du code source\&.
