.TH "Laby" 3 "Vendredi 3 Janvier 2020" "Version sp5_03.01.2020" "SDA 2019-20 Ruban de Möbius" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Laby
.SH SYNOPSIS
.br
.PP
.SS "Types publics"

.in +1c
.ti -1c
.RI "enum { \fBNBFACE\fP = 2 }"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBTab2\fP \fBfaces\fP [NBFACE]"
.br
.ti -1c
.RI "\fBVec3\fP \fBcrd_dragon\fP"
.br
.in -1c

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour SDA 2019-20 Ruban de Möbius à partir du code source\&.
