.TH "C:/PJ_SDA/labyGame.cpp" 3 "Vendredi 3 Janvier 2020" "Version sp5_03.01.2020" "SDA 2019-20 Ruban de Möbius" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/PJ_SDA/labyGame.cpp \- Composant LabyGame Structures de données et algorithmes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'labyGame\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPILE_CAP\fP   10"
.br
.ti -1c
.RI "#define \fBPILE_PAS\fP   1"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBmaj_chemin\fP (\fBPile\fP &chemin, \fBVec3\fP &nouv_crd, \fBLaby\fP &laby)"
.br
.RI "Met à jour la pile contenant les coordonnées du chemin du dragon\&. "
.ti -1c
.RI "void \fBMissionDragon\fP ()"
.br
.RI "Parcours du labyrinthe par le dragon\&. "
.in -1c
.SH "Description détaillée"
.PP 
Composant LabyGame Structures de données et algorithmes\&. 

Projet DesprésGr109NougaretGr109 
.PP
\fBAuteur\fP
.RS 4
Antoine Després, Anicet Nougaret 
.RE
.PP
\fBVersion\fP
.RS 4
1 06/01/20 
.RE
.PP

.SH "Documentation des fonctions"
.PP 
.SS "void maj_chemin (\fBPile\fP & chemin, \fBVec3\fP & nouv_crd, \fBLaby\fP & laby)"

.PP
Met à jour la pile contenant les coordonnées du chemin du dragon\&. 
.PP
\fBParamètres\fP
.RS 4
\fIchemin\fP Chemin déjà parcouru 
.br
\fInouv_crd\fP Nouvelle coordonnée à empiler 
.br
\fIlaby\fP Le labyrinthe 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour SDA 2019-20 Ruban de Möbius à partir du code source\&.
