.TH "C:/PJ_SDA/main.cpp" 3 "Vendredi 3 Janvier 2020" "Version sp5_03.01.2020" "SDA 2019-20 Ruban de Möbius" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/PJ_SDA/main.cpp \- Fonction principale du programme Structures de données et algorithmes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'labyGame\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Fonction principale du programme Structures de données et algorithmes\&. 

Projet DesprésGr109NougaretGr109 
.PP
\fBAuteur\fP
.RS 4
Antoine Després, Anicet Nougaret 
.RE
.PP
\fBVersion\fP
.RS 4
1 06/01/20 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour SDA 2019-20 Ruban de Möbius à partir du code source\&.
